METACONFIG = {
    "output": "json",
    "start_seq": 0,
    "assets_path": "assets/2-Spacesuit",
}

METADATA = {
    "name": "METAKOZO#_ID_",
    "description": "Hey, Let's hang out!",
    "external_url": "https://metakozo-dao.xyz/",
}

CONFIG = [
    {
        "id": 10,
        "name": "background",
        "directory": "10-background",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 15,
        "name": "background_item",
        "directory": "15-background_item",
        "required": True,
        "rarity_weights": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            11,
        ],
    },
    {
        "id": 18,
        "name": "back_accessory",
        "directory": "18-back_accessory",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 20,
        "name": "body",
        "directory": "20-body",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 30,
        "name": "clothes",
        "directory": "30-clothes",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 40,
        "name": "head",
        "directory": "40-head",
        "required": True,
        "rarity_weights": None,
        "link": {
            "TypeA.png": "TypeA.png",
            "TypeB.png": "TypeB.png",
            "TypeC.png": "TypeC.png",
        },
    },
    {
        "id": 50,
        "name": "eyes",
        "directory": "50-eyes",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 60,
        "name": "mouth",
        "directory": "60-mouth",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 70,
        "name": "nose",
        "directory": "70-nose",
        "required": True,
        "rarity_weights": None,
        "link": {
            "TypeA.png": "TypeA.png",
            "TypeB.png": "TypeB.png",
            "TypeC.png": "TypeC.png",
        },
    },
    {
        "id": 80,
        "name": "hair",
        "directory": "80-hair",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 100,
        "name": "ear",
        "directory": "100-ear",
        "required": True,
        "rarity_weights": None,
        "link": {
            "TypeA.png": "TypeA.png",
            "TypeB.png": "TypeB.png",
            "TypeC.png": "TypeC.png",
        },
    },
    {
        "id": 110,
        "name": "head_accessory",
        "directory": "110-head_accessory",
        "required": True,
        "rarity_weights": None,
        "link": {
            "Spacesuit_Black.png": "Spacesuit_Black.png",
            "Spacesuit_Blue.png": "Spacesuit_Blue.png",
            "Spacesuit_Camo.png": "Spacesuit_Camo.png",
            "Spacesuit_Flower.png": "Spacesuit_Flower.png",
            "Spacesuit_Gold.png": "Spacesuit_Gold.png",
            "Spacesuit_LightBlue.png": "Spacesuit_LightBlue.png",
            "Spacesuit_Red.png": "Spacesuit_Red.png",
            "Spacesuit_Silver.png": "Spacesuit_Silver.png",
            "Spacesuit_White.png": "Spacesuit_White.png",
            "Spacesuit_Yellow.png": "Spacesuit_Yellow.png",
        },
    },
    {
        "id": 120,
        "name": "hand_item",
        "directory": "120-hand_item",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 130,
        "name": "attached1",
        "directory": "130-attached1",
        "required": True,
        "rarity_weights": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            9,
        ],
    },
    {
        "id": 133,
        "name": "attached2",
        "directory": "133-attached2",
        "required": True,
        "rarity_weights": [
            1,
            9
        ],
    },
    {
        "id": 134,
        "name": "attached3",
        "directory": "135-attached3",
        "required": True,
        "rarity_weights": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            9,
        ],
    },
]
