METACONFIG = {
    "output": "json",
    "start_seq": 3000,
    "assets_path": "assets/12_Friends_santa",
}

METADATA = {
    "name": "METAKOZO FRIENDS#_ID_",
    "description": "The first commerative collection published by MKD.\n\nHolders will receive the right of access to MKD's future projects and physical events. For more information on MKD and MetaKozo, please visit https://www.metakozo-dao.xyz/",
    "external_url": "https://metakozo-dao.xyz/",
}

CONFIG = [
    {
        "id": 10,
        "name": "Background",
        "directory": "1.Background1",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 15,
        "name": "Background_item",
        "directory": "2.Background2",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 18,
        "name": "Clothes",
        "directory": "3.Clothes",
        "required": True,
        "rarity_weights": None,
        # [
        #     20,
        #     20,
        #     20,
        #     20,
        #     20,
        #     20,
        #     20,
        #     20,
        #     20,
        #     20,
        #     20,
        #     20,
        #     20,
        # ],
    },
    {
        "id": 20,
        "name": "Head",
        "directory": "4.Head",
        "required": True,
        "rarity_weights": [
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            1,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
        ],
    },
    {
        "id": 30,
        "name": "Head_Accessory",
        "directory": "5.Head_accessory",
        "required": True,
        "rarity_weights": None,
    },
]
