# This file MUST be configured in order for the code to run properly

# Make sure you put all your input images into an 'assets' folder.
# Each layer (or category) of images must be put in a folder of its own.

# CONFIG is an array of objects where each object represents a layer
# THESE LAYERS MUST BE ORDERED.

# Each layer needs to specify the following
# 1. id: A number representing a particular layer
# 2. name: The name of the layer. Does not necessarily have to be the same as the directory name containing the layer images.
# 3. directory: The folder inside assets that contain traits for the particular layer
# 4. required: If the particular layer is required (True) or optional (False). The first layer must always be set to true.
# 5. rarity_weights: Denotes the rarity distribution of traits. It can take on three types of values.
#       - None: This makes all the traits defined in the layer equally rare (or common)
#       - "random": Assigns rarity weights at random.
#       - array: An array of numbers where each number represents a weight.
#                If required is True, this array must be equal to the number of images in the layer directory. The first number is  the weight of the first image (in alphabetical order) and so on...
#                If required is False, this array must be equal to one plus the number of images in the layer directory. The first number is the weight of having no image at all for this layer. The second number is the weight of the first image and so on...

# Be sure to check out the tutorial in the README for more details.

METACONFIG = {
    "output": "json",
    "start_seq": 0,
    "assets_path": "assets/metakozo",
}

METADATA = {
    "name": "METAKOZO#_ID_",
    "description": "Hey, Let's hang out!",
    "external_url": "https://metakozo-dao.xyz/",
    # "background_color": "FFFFFF",
    #    "youtube_url": ""
}

CONFIG = [
    {
        "id": 10,
        "name": "background",
        "directory": "10-background",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 15,
        "name": "background_item",
        "directory": "15-background_item",
        "required": False,
        "rarity_weights": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            50,
        ],
    },
    {
        "id": 20,
        "name": "body",
        "directory": "20-body",
        "required": True,
        "rarity_weights": [
            1,
            4,
            4,
        ]
    },
    {
        "id": 30,
        "name": "clothes",
        "directory": "30-clothes",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 40,
        "name": "head",
        "directory": "40-head",
        "required": True,
        "rarity_weights": None,
        "link": {
            "TypeA.png": "TypeA.png",
            "TypeB.png": "TypeB.png",
            "TypeC.png": "TypeC.png",
        },
    },
    {
        "id": 50,
        "name": "eyes",
        "directory": "50-eyes",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 60,
        "name": "mouth",
        "directory": "60-mouth",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 70,
        "name": "nose",
        "directory": "70-nose",
        "required": True,
        "rarity_weights": None,
        "link": {
            "TypeA.png": "TypeA.png",
            "TypeB.png": "TypeB.png",
            "TypeC.png": "TypeC.png",
        },
    },
    {
        "id": 80,
        "name": "hair",
        "directory": "80-hair",
        "required": True,
        "rarity_weights": None,
    },
    {
        "id": 90,
        "name": "face_accessory",
        "directory": "90-face_accessory",
        "required": False,
        "rarity_weights": [
            100,
            10,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            10,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            10,
            100,
            100,
            4000,  # none
        ],
        "remove": ['eyes'],
    },
    {
        "id": 100,
        "name": "ear",
        "directory": "100-ear",
        "required": True,
        "rarity_weights": None,
        "link": {
            "TypeA.png": "TypeA.png",
            "TypeB.png": "TypeB.png",
            "TypeC.png": "TypeC.png",
        },
    },
    {
        "id": 110,
        "name": "head_accessory",
        "directory": "110-head_accessory",
        "required": False,
        "rarity_weights": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            40,  # none
        ],
    },
    {
        "id": 120,
        "name": "hand_item",
        "directory": "120-hand_item",
        "required": False,
        "rarity_weights": [
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            100,
            5,
            5,
            5,
            100,
            100,
            1,
            100,
            100,
            100,
            100,
            1,
            100,
            100,
            100,
            100,
            4000,  # none.png
        ],
    },
    {
        "id": 130,
        "name": "attached1",
        "directory": "130-attached1",
        "required": False,
        "rarity_weights": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            28,
        ],
    },
    {
        "id": 133,
        "name": "attached2",
        "directory": "133-attached2",
        "required": False,
        "rarity_weights": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            18,
        ],
    },
    {
        "id": 134,
        "name": "attached3",
        "directory": "135-attached3",
        "required": False,
        "rarity_weights": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            38,
        ],
    },
    {
        "id": 140,
        "name": "personality",
        "directory": "140-personality",
        "required": True,
        "rarity_weights": None,
    },
]
